### ISSUE TITLE
Release proto-compiler-plugin to pypi

### ISSUE THREAD

**Issue by ethanbao** [googleapis/proto-compiler-plugin#14]
Artman Dockerfile can then install proto-compiler-plugin from pypi directly.

**Comment by michaelbausor** [comment]
I agree, we should do this very soon. The only thing I think that needs to be resolved is the name to publish under - proto-compiler-plugin is too generic for PyPI

My candidate names are:
- googleapis-protoc-plugin
- googleapis-protoc-plugin-java
- googleapis-protoc-resourcenames

Any thoughts on those, or other suggestions? cc @garrettjonesgoogle @shinfan @lukesneeringer @geigerj

Once this is done, it should also be possible to add this directly as a dependency of artman, so that it can be removed from the Dockerfile completely.

**Comment by lukesneeringer** [comment]
At the risk of bikeshedding, I agree with @michaelbausor.

Does this package have use outside of artman? Another option is to not name it at all, and just vendor it inside artman.

**Comment by lukesneeringer** [comment]
Screw it, bikeshedding all the way. Is this a wood or a metal bikeshed?

After discussing with @michaelbausor, `protoc-java-resource-names-plugin`.
Yes, the name is friggin' _War and Peace_, but at least no normal person ever uses this, so whatever.

Dropping the `googleapis` prefix just to keep an inch of sanity on name length, though.

**Comment by ethanbao** [comment]
By reading the name, it sounds like the plugin is needed for grpc/java generation even without gapic wrapper. Is that true?

**Comment by michaelbausor** [comment]
Yes. Of course, it is not **needed** - generation with protoc works without the plugin. But our published packages of generated proto classes include the resource names generated by the plugin, so any artman Java generation, even of just protos and no GAPIC, needs the plugin

**Comment by michaelbausor** [comment]
This is now published here: https://pypi.python.org/pypi/protoc-java-resource-names-plugin/0.0.2
